name: CI test

on:
  push: 
    branches: ["main"]

jobs: 
  test-ci:
    runs-on: ubuntu-latest 

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ci-test-s3
          aws-region: us-east-1

      - name: Add files to bucket
        run: |
          aws s3 sync . s3://test-ci-bmf \
          --exclude ".git/*" \
          --exclude "README.md" \
          --exclude ".github/*"
