name: CLI test

on:
  push: 
    branches: ["main"]

jobs: 
  test-cli:
    runs-on: ubuntu-latest 

    permissions:
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::011215723408:role/ci-test-s3
          aws-region: us-east-1

      - name: add to bucket
        run: aws s3 sync . s3://test-ci-bmf --exclude ".git/*"
